name: Generate Badge and Build

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build
        working-directory: ./build

      - name: Generate Badge
        run: node build/index.js
        working-directory: ./build

      - name: Commit Results
        run: |
          git config --global user.name devYuMinKim
          git config --global user.email gimyumin40@gmail.com
          git add .
          git commit -m 'Update badge and build [skip ci]'
          git push
        working-directory: ./public

