name: Scrapping blog posts

on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Git identity
        run: |
          git config --global user.name 'yuminnk'
          git config --global user.email 'gimyumin40@gmail.com'
        env:
          GIT_AUTH_TOKEN: x-access-token:${{ secrets.GH_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run Docker image
        run: |
          docker build -t blog_scraper .
          docker run --env URL="https://yuminnk-devlog.vercel.app" --env CSS_SELECTOR="#__next>div:nth-child(2)>div>div.notion-frame>div>main>div.notion-page-content>article>div.notion-collection.notion-block-52c3f72df427430ca4768e53c36a61c6>div:nth-child(2)>div>div" blog_scraper

      - name: Copy updated JSON files
        run: |
          docker cp $(docker ps -lq):/app/latest-post.json .
          docker cp $(docker ps -lq):/app/latest-posts.json .
          docker cp $(docker ps -lq):/app/random-post.json .
          docker cp $(docker ps -lq):/app/random-posts.json .

      - name: Commit changes
        run: |
          git add *.json
          git commit -m "Updated JSON files with recent blog posts"
          git push origin main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTH_TOKEN: x-access-token:${{ secrets.GH_TOKEN }}
